version: '3.8'

services:
  artheon-backend:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: artheon-sast-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=production
    volumes:
      - /:/host:ro

volumes:
  app_data:
